[env:esp32_a]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -D DEVICE_ID=\"ESP32-A\"
upload_port = COM8
monitor_port = COM8

[env:esp32_b]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -D DEVICE_ID=\"ESP32-B\"