[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4

[env:esp32_a]
build_flags = -D DEVICE_ID=\"ESP32-A\"
upload_port = COM3
monitor_port = COM3

[env:esp32_b]
build_flags = -D DEVICE_ID=\"ESP32-B\"
upload_port = COM4
monitor_port = COM4