[env:esp32_a]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -D DEVICE_ID=\"ESP32-A\"
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3

[env:esp32_b]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -D DEVICE_ID=\"ESP32-B\"
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4